# Generated by Django 5.2.8 on 2025-11-19 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta al público.', max_digits=12)),
                ('categoria', models.CharField(blank=True, help_text='Ej: entrada, principal, postre...', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
                ('es_base', models.BooleanField(default=False, help_text='Marca si esta unidad es una de las unidades base del sistema.')),
                ('factor_base', models.DecimalField(decimal_places=4, help_text="Factor para convertir a la unidad base del sistema. Ej: si la base es 'g', 1 kg = 1000 g → factor_base = 1000.", max_digits=10)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad mínima recomendada en unidad del insumo.', max_digits=12)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad máxima recomendada en unidad del insumo.', max_digits=12, null=True)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado por unidad.', max_digits=12)),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='inventory.proveedor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventory.unidadmedida')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria por unidad de plato, en unidad del insumo.', max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='inventory.insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_insumos', to='inventory.plato')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'unique_together': {('plato', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad disponible en este almacén, en unidad del insumo.', max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado por unidad para este insumo en este almacén (puede diferir del costo promedio global del insumo).', max_digits=12)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.almacen')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Stock de insumo',
                'verbose_name_plural': 'Stocks de insumos',
                'unique_together': {('insumo', 'almacen')},
            },
        ),
    ]
