# Generated by Django 5.2.8 on 2025-11-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de insumo',
                'verbose_name_plural': 'Categorías de insumo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría general del insumo (ej: Carnes, Abarrotes, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='inventory.categoriainsumo'),
        ),
    ]
