# Generated by Django 5.2.8 on 2025-11-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categoriainsumo_insumo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por compra'), ('ENTRADA_AJUSTE', 'Entrada por ajuste'), ('SALIDA_AJUSTE', 'Salida por ajuste')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad del movimiento. Positiva para entrada, negativa para salida.', max_digits=14)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, help_text='Costo unitario asociado al movimiento. Obligatorio para entradas de compra. Puede ser nulo en ciertos ajustes/salidas.', max_digits=12, null=True)),
                ('costo_total', models.DecimalField(decimal_places=4, default=0, help_text='Costo total del movimiento (cantidad * costo_unitario) cuando aplica.', max_digits=14)),
                ('fecha_movimiento', models.DateTimeField(help_text='Fecha efectiva del movimiento (puede diferir de la creación del registro).')),
                ('motivo', models.TextField(blank=True, help_text='Descripción o motivo del movimiento (ej: ajuste inventario, corrección, etc.).')),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa, número de documento, factura, etc.', max_length=100)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.almacen')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.insumo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha_movimiento', '-created_at'],
            },
        ),
    ]
