# Generated by Django 5.2.8 on 2025-11-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de unidad de consumo incluida en 1 unidad de compra. Ej: saco 25kg → consumo en gramos → 25,000.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_compra',
            field=models.ForeignKey(blank=True, help_text='Unidad en que se compra este insumo (ej: saco, litro, bandeja).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_compra', to='inventory.unidadmedida'),
        ),
    ]
