# Generated by Django 5.2.8 on 2025-11-24 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_insumo_factor_conversion_insumo_unidad_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lote', models.CharField(blank=True, help_text='Identificador de lote entregado por proveedor o interno.', max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del lote (si aplica).', null=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad disponible de este lote en unidad de consumo.', max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Costo unitario en unidad de consumo para este lote.', max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='Permite desactivar lotes antiguos o cerrados.')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventory.almacen')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Lote de insumo',
                'verbose_name_plural': 'Lotes de insumos',
                'ordering': ['fecha_vencimiento', 'numero_lote'],
                'unique_together': {('insumo', 'almacen', 'numero_lote', 'fecha_vencimiento')},
            },
        ),
    ]
