# Generated by Django 5.2.8 on 2025-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_loteinsumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetainsumo',
            options={'ordering': ['plato', 'insumo'], 'verbose_name': 'Ingrediente de receta', 'verbose_name_plural': 'Ingredientes de receta'},
        ),
        migrations.AddField(
            model_name='plato',
            name='costo_receta',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo total de la receta para una porción/unidad del plato.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej: entrada, principal, postre...', max_length=100),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad necesaria por unidad de plato, en unidad del insumo.', max_digits=12),
        ),
    ]
