# Generated by Django 5.2.8 on 2025-12-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_recetainsumo_options_plato_costo_receta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de plato',
                'verbose_name_plural': 'Categorías de plato',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por compra'), ('ENTRADA_AJUSTE', 'Entrada por ajuste'), ('SALIDA_AJUSTE', 'Salida por ajuste'), ('ENTRADA_TRASPASO', 'Entrada por traspaso'), ('SALIDA_TRASPASO', 'Salida por traspaso'), ('SALIDA_CONSUMO_RECETA', 'Salida por consumo de receta'), ('SALIDA_MERMA', 'Salida por merma')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Tipo de plato (ej: entrada, principal, postre, menú ejecutivo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platos', to='inventory.categoriaplato'),
        ),
    ]
