# Generated by Django 5.2.8 on 2025-12-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_categoriaplato_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_documento', models.DateField(help_text='Fecha de la factura / guía de compra.')),
                ('numero_documento', models.CharField(blank=True, help_text='Número de factura/boleta/guía.', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad comprada en unidad de consumo del insumo.', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, help_text='Costo unitario en moneda local (por unidad de consumo).', max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Referencia interna opcional (OC, nota, etc.).', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('procesada', models.BooleanField(default=False, editable=False, help_text='Indica si ya se generó la entrada de inventario.')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='inventory.almacen')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='inventory.insumo')),
                ('movimiento', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_compra', to='inventory.movimientoinventario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='inventory.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de compra',
                'verbose_name_plural': 'Entradas de compra',
                'ordering': ['-fecha_documento', '-created_at'],
            },
        ),
    ]
