# Generated by Django 5.2.8 on 2025-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_entradacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento declarada para este lote', null=True),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='numero_lote',
            field=models.CharField(blank=True, help_text='Número de lote del proveedor', max_length=100, null=True),
        ),
    ]
