# Generated by Django 5.2.8 on 2025-12-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_entradacompra_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(blank=True, help_text='Almacén o sede para el cual se planifica el menú.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_menu', to='inventory.almacen')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('once', 'Once / Merienda')], default='almuerzo', max_length=20)),
                ('porciones_planificadas', models.DecimalField(decimal_places=2, help_text='Número de platos estimados para este día/servicio.', max_digits=12)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.menuplan')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_menu', to='inventory.plato')),
            ],
            options={
                'ordering': ['fecha', 'servicio'],
            },
        ),
    ]
