# Generated by Django 5.2.8 on 2025-12-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_menuplan_menuplanitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuplanitem',
            options={'ordering': ['fecha', 'plato__nombre']},
        ),
        migrations.RemoveField(
            model_name='menuplanitem',
            name='servicio',
        ),
        migrations.AddField(
            model_name='menuplanitem',
            name='categoria_plato',
            field=models.ForeignKey(default=1, help_text='Categoría del plato en este plan (ej: Principal, Ensalada, Postre).', on_delete=django.db.models.deletion.PROTECT, related_name='items_menu', to='inventory.categoriaplato'),
            preserve_default=False,
        ),
    ]
