# Generated by Django 5.2.8 on 2025-12-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_menuplanitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrado', 'Cerrado'), ('ajustado', 'Ajustes aplicados')], default='borrador', max_length=20)),
                ('tolerancia_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Tolerancia en % para considerar las diferencias aceptables.', max_digits=5)),
                ('tolerancia_unidades', models.DecimalField(blank=True, decimal_places=3, help_text='Tolerancia absoluta en unidades (opcional).', max_digits=12, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventory.almacen')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo de inventario',
                'verbose_name_plural': 'Conteos de inventario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConteoInventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_sistema', models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad de sistema al momento de conciliar (snapshot).', max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dentro_tolerancia', models.BooleanField(default=False, help_text='Indica si la diferencia está dentro de la tolerancia definida.')),
                ('comentarios', models.CharField(blank=True, max_length=255)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.conteoinventario')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_items', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Ítem de conteo de inventario',
                'verbose_name_plural': 'Ítems de conteo de inventario',
                'unique_together': {('conteo', 'insumo')},
            },
        ),
    ]
