# Generated by Django 5.2.8 on 2025-12-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_conteoinventario_conteoinventarioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que pueden operar este almacén.', related_name='almacenes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
    ]
