# Generated by Django 5.2.8 on 2025-12-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0013_almacen_usuarios_conteoinventario_aprobado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_supervisor_inventario', models.BooleanField(default=False, help_text='Puede aprobar conteos con diferencias críticas y aplicar ajustes.')),
                ('acceso_todos_los_almacenes', models.BooleanField(default=False, help_text='Puede ver y operar todos los almacenes sin necesidad de estar asignado en ellos.')),
                ('puede_cerrar_conteos', models.BooleanField(default=False, help_text='Puede cerrar conteos de inventario (sin necesidad de ser supervisor).')),
                ('puede_aplicar_ajustes', models.BooleanField(default=False, help_text="Puede ejecutar la acción de 'Aplicar ajustes de inventario' en los conteos.")),
                ('puede_ver_costos', models.BooleanField(default=False)),
                ('puede_editar_costos', models.BooleanField(default=False)),
                ('puede_gestionar_insumos', models.BooleanField(default=False)),
                ('puede_gestionar_recetas', models.BooleanField(default=False)),
                ('grupo', models.OneToOneField(help_text='Seleccione el grupo al que desea asignar permisos especiales.', on_delete=django.db.models.deletion.CASCADE, related_name='rol_especial', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol especial',
                'verbose_name_plural': 'Roles especiales',
            },
        ),
    ]
