# Generated by Django 5.2.8 on 2025-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rolespecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteoinventario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('cerrado', 'Cerrado'), ('ajustado', 'Ajustes aplicados'), ('pendiente_aprobacion', 'Pendiente de aprobación')], default='borrador', max_length=20),
        ),
    ]
