# Generated by Django 5.2.8 on 2025-12-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_conteoinventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteoinventario',
            name='tolerancia_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tolerancia en % para considerar las diferencias aceptables.', max_digits=5, null=True),
        ),
    ]
